media: ipu6: Fix up missing IWYU issue
In -next:

/tmp/next/build/drivers/media/pci/intel/ipu6/ipu7-fw-isys.c:229:3: error: call to undeclared function 'clflush_cache_range'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  229 |                 clflush_cache_range(cpu_mapped_buf, size);
      |                 ^

Signed-off-by: Mark Brown <broonie@kernel.org>